apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openpayd-website
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: openpayd-website
    spec:
      containers:
      - name: openpayd-website-pod
        image: richardcatania/openpayd:latest
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openpayd-website-service
spec:
  selector:
    app: openpayd-website
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
